### ISSUE TITLE
ode review ACASXu repair

### ISSUE THREAD

**Issue by TomyYamy** [Shaddadi/veritex#12]
I understand you make some list by 
acasxu_repair_list.py
At least, we may merge the codes repair_propertyX.py into repair_property.py.
I know you need repair_propertyX.py as function pointer for property_ls. You can keep this. but still you may call marged code repair_property.py internal of  repair_propertyX.py.

repair_all_nnets.py and repair_sub_nnets.py are almost same. just marge it and make shell script to call all setting or sub setting.

**Comment by Shaddadi** [comment]
Thanks for the suggestion. It has been modified
