### ISSUE TITLE
Save output of reproduce_results to a log file

### ISSUE THREAD

**Issue by bardhh** [Shaddadi/veritex#21]
It would be useful to have all the outputs stored in a log file, particularly for debugging purposes in case some issue occurs.

**Comment by ttj** [comment]
Possibly for this just update the instructions (commands) to pipe to an output file?

Here is what I got from running the reproduce 1 (on a Windows host), attached

Additionally, do you copy the figures back to the host after execution? If so, where are they? I see the tables pretty clearly in the output at the end from the attached log, but wasn't sure on the figures.

[taylor.txt](https://github.com/Shaddadi/veritex/files/8622417/taylor.txt)

**Comment by Shaddadi** [comment]
I  added a command to export the results generated in Docker to the host
