### ISSUE TITLE
Reproduce_results2.py generates an error

### ISSUE THREAD

**Issue by bardhh** [Shaddadi/veritex#23]
I ran Reproduce_results2.py for several hours. Here is the log (partial since buffer on powershell is limited). 

I got the following error: "The number of repaired instances is not correct!"

[log.txt](https://github.com/Shaddadi/veritex/files/8617595/log.txt)

**Comment by Shaddadi** [comment]
Can you share the file 'neural_network_repair.log'? It is in 'examples/ACASXu/repair/logs'

**Comment by bardhh** [comment]
It is empty.

**Comment by bardhh** [comment]
Here are all the logs. 

[logs.zip](https://github.com/Shaddadi/veritex/files/8617664/logs.zip)

**Comment by Shaddadi** [comment]
The bug is fixed
